### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [WandererYeh/TDDDay1#1]
測試案例寫得不錯，清楚易懂。

幾點建議如下：
1. 這邊應該用 ShouldEqual() 而不是 ShouldMatch()
2. field 用字串搭配 reflection 是常見的彈性作法，要額外小心的是字串大小寫的問題。

這邊也提供我的 sample solution 給您參考：http://bit.ly/91-tdd-day1-homework-solution
第一版是只 support Product,  第二版則是透過 extension method + generic + lambda 來 support 任意型別。API好用，語意清楚以外，production code 的寫法我也有刻意重構到很簡潔，可以參考一下。

**Comment by WandererYeh** [comment]
感謝91哥，issue已調整
